# Generated by Django 4.1.7 on 2023-03-03 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generating_csv', '0006_alter_column_data_scheme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datascheme',
            name='file',
        ),
    ]
